version: '3.8'

services:
  app:
    profiles: ['app']
    container_name: users-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
    networks:
      - users-api
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ./logs:/app/logs
    logging:
      driver: 'local'

  postgres:
    container_name: postgres-${PROJECT_NAME}
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_ROL=${POSTGRES_ROL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - users-api
    restart: always

  postgres-test:
    container_name: postgres-test-${PROJECT_NAME}
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_ROL=${POSTGRES_ROL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - postgres-test:/data/postgres
    ports:
      - '${POSTGRES_PORT_TEST}:5432'
    networks:
      - users-api
    restart: always

  pgadmin:
    container_name: pgadmin-${PROJECT_NAME}
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - '${PGADMIN_PORT}:80'
    networks:
      - users-api
    restart: always

  redis:
    container_name: redis-${PROJECT_NAME}
    image: bitnami/redis:6.2.7
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - users-api
  redis-commander:
    container_name: redis-commander-${PROJECT_NAME}
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis-${PROJECT_NAME}
      REDIS_HOST: redis-${PROJECT_NAME}
      REDIS_PORT: redis:${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: ${REDIS_COMMANDER_USER}
      HTTP_PASSWORD: ${REDIS_COMMANDER_PASSWORD}
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    networks:
      - users-api

  rabbitmq:
    image: rabbitmq:3.7.28-management
    container_name: rabbitmq-${PROJECT_NAME}
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-root}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-root}
    ports:
      - ${RABBITMQ_PORT}:5672 #amqp
      - 15672:15672 #http
      - 15692:15692 #prometheus
    networks:
      - users-api

networks:
  users-api:
    driver: bridge

volumes:
  postgres:
  postgres-test:
  pgadmin:
  redis:
  redis-config:
  rabbitmq:
