export enum DomainErrorCode {
  ID_PATH_PARAMETER_MISSING = 'ID_PATH_PARAMETER_MISSING',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  DTO_PROPERTIES_ERROR = 'DTO_PROPERTIES_ERROR',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  DATABASE_ERROR = 'DATABASE_ERROR'
}
